# Generated by Django 5.1.6 on 2025-03-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'permissions': [('view_machineinventory', 'Can view machine inventory'), ('add_machineinventory', 'Can add machine inventory'), ('change_machineinventory', 'Can change machine inventory'), ('delete_machineinventory', 'Can delete machine inventory')]},
        ),
    ]
