# Generated by Django 5.1.6 on 2025-03-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_machine_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={},
        ),
    ]
