# Generated by Django 5.1.7 on 2025-04-01 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VippsCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('test', 'Test Environment'), ('production', 'Production Enviroment')], default='test', max_length=10)),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=225)),
                ('subscription_key', models.CharField(max_length=100)),
                ('merchant_serial_number', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Vipps Credentials',
                'unique_together': {('organization', 'environment')},
            },
        ),
    ]
