# Generated by Django 5.1.7 on 2025-04-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vippscredentials',
            options={'verbose_name': 'Vipps Credential', 'verbose_name_plural': 'Vipps Credentials'},
        ),
        migrations.AlterField(
            model_name='vippscredentials',
            name='environment',
            field=models.CharField(choices=[('test', 'Test Environment'), ('production', 'Production Environment')], default='test', max_length=10),
        ),
    ]
