# Generated by Django 5.1.7 on 2025-04-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VippsCredentials',
        ),
    ]
