# Generated by Django 5.1.6 on 2025-04-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_delete_vippscredentials"),
        ("transactions", "0003_coupon"),
    ]

    operations = []
